# API Name
name: ImageManagerAPI
# Log folder location
# Do add '/' in the end
logAddr: log/
# Img folder location
# Do add '/' in the end
imgAddr: img/
# True if running in production
# False if running in development
production: false
# Database config
database:
  addr: 127.0.0.1
  name: ImageManagerAPI
  user: root
  pass: 1234567890
# Server config
server:
  port: 8082
  # Unit: Seconds
  readTimeout: 10
  writeTimeout: 10
  # Unit: MB
  maxHeaderBytes: 1
