# API Name
name: ImageManagerAPI
# Log folder location ex:
# Do add '/' in the end
logAddr: log/
# True if running in production
# False if running in development
production: false
# Server config
server:
  port: 8082
  # Unit: Seconds
  readTimeout: 10
  writeTimeout: 10
  # Unit: MB
  maxHeaderBytes: 1
